{{- if .Values.persistence.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "strapi.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "strapi.name" . }}
    helm.sh/chart: {{ include "strapi.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- if .Values.persistence.storageClass }}
{{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- end -}}

# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: strapi-pvc
#   labels:
#     app: strapi
# spec:
# #   storageClassName: sio-small
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi