apiVersion: v1
kind: Secret
metadata:
  name: {{ template "strapi.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "strapi.name" . }}
    helm.sh/chart: {{ include "strapi.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
{{- if .Values.externalMongodbUrl }}
  mongo-uri: {{ .Values.externalMongodbUrl | b64enc | quote }}
  mongo-oplog-uri: {{ required "Please specify the external MongoDB OpLog URL" .Values.externalMongodbOplogUrl | b64enc | quote }}
{{- else }}
  {{- $fullname := include "mongodb.fullname" . -}}
  {{- $username := required "Please specify a MongoDB username" .Values.mongodb.mongodbUsername }}
  {{- $password := required "Please specify a MongoDB password" .Values.mongodb.mongodbPassword }}
  {{- $rootPassword := required "Please specify a MongoDB password" .Values.mongodb.mongodbRootPassword }}
  {{- $rsName := .Values.mongodb.replicaSet.name }}
  {{- $port := .Values.mongodb.service.port }}
  {{- $dbname := required "Please specify a MongoDB database" .Values.mongodb.mongodbDatabase }}
  mongo-password: {{ .Values.mongodb.mongodbPassword | b64enc | quote }}
  mongo-uri: {{ printf "mongodb://%s:%s@%s-mongodb:%.0f/%s" $username $password $fullname $port $dbname | b64enc | quote }}
  mongo-oplog-uri: {{ printf "mongodb://root:%s@%s-mongodb:%.0f/local?replicaSet=%s&authSource=admin" $rootPassword $fullname $port $rsName | b64enc | quote }}
{{- end }}